package services

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"caddy_server/database"
)

func parseJSON(s string, v interface{}) error {
	return json.Unmarshal([]byte(s), v)
}

func GenerateSiteConfig(site database.Site) string {
	var b strings.Builder

	b.WriteString("# ===================================================\n")
	b.WriteString(fmt.Sprintf("# Auto-generated by Caddy Server Manager\n"))
	b.WriteString(fmt.Sprintf("# Site ID: %d | Name: %s\n", site.ID, site.Name))
	b.WriteString("# DO NOT EDIT MANUALLY\n")
	b.WriteString("# ===================================================\n\n")
	b.WriteString(fmt.Sprintf("%s {\n", site.Domain))

	if site.RequestHeaders != "" && site.RequestHeaders != "[]" {
		var headers []struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		}
		if err := parseJSON(site.RequestHeaders, &headers); err == nil {
			for _, h := range headers {
				if h.Name != "" {
					b.WriteString(fmt.Sprintf("    header_up %s %s\n", h.Name, h.Value))
				}
			}
		}
	}

	if site.PathRoutes != "" && site.PathRoutes != "[]" {
		var routes []struct {
			Path string `json:"path"`
			To   string `json:"to"`
		}
		if err := parseJSON(site.PathRoutes, &routes); err == nil {
			for _, r := range routes {
				if r.Path != "" && r.To != "" {
					path := strings.TrimSuffix(r.Path, "/")
					b.WriteString(fmt.Sprintf("    handle_path %s/* {\n", path))
					b.WriteString(fmt.Sprintf("        reverse_proxy %s\n", r.To))
					b.WriteString("    }\n")
				}
			}
		}
	}

	b.WriteString(fmt.Sprintf("    reverse_proxy %s\n", site.ProxyTo))

	if site.Compression == 1 {
		b.WriteString("    encode gzip\n")
	}

	if site.ExtraConfig != "" {
		b.WriteString(fmt.Sprintf("    %s\n", site.ExtraConfig))
	}

	b.WriteString("}\n")
	return b.String()
}

func WriteSiteConfig(site database.Site, sitesDir string) error {
	filename := fmt.Sprintf("%s/%s.conf", sitesDir, site.Domain)
	content := GenerateSiteConfig(site)

	if err := os.MkdirAll(sitesDir, 0755); err != nil {
		return fmt.Errorf("创建子配置目录失败: %w", err)
	}

	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入子配置文件失败: %w", err)
	}

	return nil
}

func GenerateMainCaddyfile(serverDomain, sitesDir string) string {
	var b strings.Builder
	b.WriteString("# ===================================================\n")
	b.WriteString("# Caddy Server Manager - Main Caddyfile\n")
	b.WriteString("# ===================================================\n\n")

	if serverDomain != "" {
		b.WriteString(fmt.Sprintf("%s {\n", serverDomain))
		b.WriteString("    reverse_proxy localhost:8080\n")
		b.WriteString("}\n\n")
	}

	b.WriteString(fmt.Sprintf("import %s/*.conf\n", sitesDir))
	return b.String()
}

func WriteMainCaddyfile(caddyfilePath, serverDomain, sitesDir string) error {
	content := GenerateMainCaddyfile(serverDomain, sitesDir)

	dir := caddyfilePath[:strings.LastIndex(caddyfilePath, "/")]
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("创建 Caddyfile 目录失败: %w", err)
	}

	if err := os.WriteFile(caddyfilePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入主 Caddyfile 失败: %w", err)
	}

	return nil
}

func DeleteSiteConfig(domain, sitesDir string) error {
	filename := fmt.Sprintf("%s/%s.conf", sitesDir, domain)
	if err := os.Remove(filename); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("删除子配置文件失败: %w", err)
	}
	return nil
}

func RegenerateAllSites(sitesDir string) error {
	rows, err := database.DB.Query(`
		SELECT id, name, domain, scheme, proxy_to, compression, request_headers, path_routes, extra_config, status
		FROM t_site WHERE delete_time = 0 AND status = 'enabled'
	`)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var site database.Site
		rows.Scan(&site.ID, &site.Name, &site.Domain, &site.Scheme, &site.ProxyTo,
			&site.Compression, &site.RequestHeaders, &site.PathRoutes, &site.ExtraConfig, &site.Status)
		if err := WriteSiteConfig(site, sitesDir); err != nil {
			return err
		}
	}
	return nil
}
